### ISSUE TITLE
Installation Section

### ISSUE THREAD

**Issue by lfarah** [team-pie/DDDKit#1]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks an ```Installation Section```
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an ```Installation Section```
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by lfarah** [comment]
https://github.com/vsouza/awesome-ios/pull/1342

**Comment by gsabran** [comment]
thanks @lfarah There's an installation section in the wiki, so I'll add one in the readme that will point to it. Does that sounds good?

**Comment by lfarah** [comment]
I think it's good the way it is!
